### ISSUE TITLE
Onboarding experience

### ISSUE THREAD

**Issue by johnrudolph** [inxilpro/disastercheckin.com#2]
When we receive a message from any number that we don't yet have in the db, we need to ask them to opt in.

- [ ] After their first message, send a message explaining what the service is {{ tbd on wording), and what the available commands are {{ tbd on commands }}
- [ ] If their message contains no keywords, reply with "Here are the key words". Basically the same as the "Help" keyword

**Comment by belzaaron** [comment]
Coming from Twilio:
```
#parameters: array:20 [▼
  "ToCountry" => "US"
  "ToState" => "NC"
  "SmsMessageSid" => "SMb636ddd1145fa485c2955081811ce627"
  "NumMedia" => "0"
  "ToCity" => null
  "FromZip" => "19611"
  "SmsSid" => "SMb636ddd1145fa485c2955081811ce627"
  "FromState" => "PA"
  "SmsStatus" => "received"
  "FromCity" => "READING"
  "Body" => "Hi"
  "FromCountry" => "US"
  "To" => "+18288880440"
  "MessagingServiceSid" => "MG8906a0d53042fe5da25a86474f7e6b15"
  "ToZip" => null
  "NumSegments" => "1"
  "MessageSid" => "SMb636ddd1145fa485c2955081811ce627"
  "AccountSid" => "ACb23d55d6d8e5f84ff488dbc6bf9c2160"
  "From" => "+0000000000"
  "ApiVersion" => "2010-04-01"
]
```

`POST`'s to: `/webhooks/twilio`.
