### ISSUE TITLE
Send latest update to SMS request

### ISSUE THREAD

**Issue by johnrudolph** [inxilpro/disastercheckin.com#6]
NOTE: This is a cool idea for later. Don't do this yet. 

If we receive a SMS with the keyword "Search", we return the latest update from that phone number, if we have it. 

Note, we will probably need to normalize the string for the phone number. 

If we don't have the phone number, give them the URL to the site and tell them to check back in in 24 hours.

**Comment by edgrosvenor** [comment]
@johnrudolph I put some quick and dirty normalization directly in the search controller we built for the web interface, so I'll extract that into an action that we can use to do normalization everywhere. It's very rough, but it works. Extracting it to an action class will let us use it everywhere and make it more robust in one location.

**Comment by DanielCoulbourne** [comment]
Search by SMS is now added.
